# Generated by Django 5.0.3 on 2024-05-12 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='imageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='listing_image/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='listing_image/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='listing_image/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='listing_image/')),
            ],
        ),
        migrations.CreateModel(
            name='listingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=64)),
                ('barangay', models.CharField(max_length=64)),
                ('municipality', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('postalCode', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='listingFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.BooleanField()),
                ('nearbyLaundry', models.BooleanField()),
                ('nearbyTransit', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('bathroom', models.BooleanField()),
                ('kitchen', models.BooleanField()),
                ('airConditioning', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('curfew', models.BooleanField()),
                ('visitor', models.BooleanField()),
                ('maleOnly', models.BooleanField()),
                ('femaleOnly', models.BooleanField()),
                ('accessibility', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='paymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advancePayment', models.IntegerField()),
                ('securityDeposit', models.IntegerField()),
                ('minimumStay', models.IntegerField()),
                ('utilityPayment', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='rateReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=8, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=0)),
                ('is_landowner', models.BooleanField(blank=True, default=0, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urating', to='cribconnect.ratereviews')),
            ],
        ),
        migrations.CreateModel(
            name='forVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontPhoto', models.ImageField(upload_to='for_verification/')),
                ('backPhoto', models.ImageField(upload_to='for_verification/')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribconnect.account')),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(max_length=16)),
                ('price', models.BigIntegerField()),
                ('dimension', models.IntegerField()),
                ('primaryImage', models.ImageField(upload_to='listing_image/')),
                ('is_available', models.BooleanField(default=1)),
                ('images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cribconnect.imagegallery')),
                ('landowner', models.ManyToManyField(to='cribconnect.account')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribconnect.listingaddress')),
                ('features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cribconnect.listingfeatures')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribconnect.paymentterms')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prating', to='cribconnect.ratereviews')),
            ],
        ),
        migrations.CreateModel(
            name='inquiryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(max_length=16)),
                ('requestStatus', models.CharField(default='Pending', max_length=16)),
                ('from_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_userID', to='cribconnect.account')),
                ('to_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_userID', to='cribconnect.account')),
                ('listingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cribconnect.listing')),
            ],
        ),
        migrations.CreateModel(
            name='cribshare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribconnect.account')),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cribconnect.listing')),
            ],
        ),
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribconnect.listing')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cribconnect.account')),
            ],
        ),
    ]
